version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker info
      - run: docker-compose --version
      - run: sudo curl -L https://github.com/docker/compose/releases/download/1.17.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
      # add docker templates
      - run:
          name: add docker templates
          command: |
            make login dockerize
      # with credentials stored in the UI
      - run:
          name: Build application Docker image
          command: |
            make clean-all login build
      - run:
          name: Run lint
          command: |
            make lint
      - run:
          name: Run tests
          command: |
            make test
      - run:
          name: Push Docs
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              make docs docs-push
            fi
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              make push
            fi
# org-global for global env vars
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: org-global
